#!/bin/bash
#-
#- usage
#-
#-

ADADMIN="$4"
ADADMINPASS="$5"
ADDOMAIN="$6"
ADMINGROUPS="$7"
EXECDIR="$( dirname "$0" )"
IAM="$( whoami )"

function scriptLogging(){
    local logfile scriptname timestamp label mode
    logfile="/tmp/unbind_AD_then_bind_AD.log"
    scriptname="$( /usr/bin/basename "$0" )"
    timestamp="$( /bin/date "+%F %T" )"
    mode="$2"
    case "${mode:-1}" in
        2 )
            label="[error]"
            echo "$timestamp $scriptname $label $1" | /usr/bin/tee -a "$logfile"
            ;;
        * )
            label="[info]"
            echo "$timestamp $scriptname $label $1" | /usr/bin/tee -a "$logfile"
            ;;
    esac
}

function usage(){
    grep "^#-" "$0" | cut -c 4-
}

if [ $IAM != root ]; then
	usage ; exit 1
fi

computerName="$( dsconfigad -show | awk '$1 == "computername" {print $3}' | tr -d '$' )"
if [ -z "$computerName" ]; then
    scriptLogging "This computer is not bound to Active Directory domain."
    scriptLogging "Nothing to do for this computer."
    exit 0
else
    scriptLogging "ComputerID: $computerName"
    systemsetup -setcomputername "${computerName}"
    systemsetup -setlocalsubnetname "$(echo "${computerName}" | tr "[:upper:]" "[:lower:]")"
fi

dsconfigad -remove -username "${ADADMIN}" -password "${ADADMINPASS}" 2>&1
dsconfigad -add "${ADDOMAIN}" -username "${ADADMIN}" -password "${ADADMINPASS}" -computer "${COMPUTERID}" 2>&1
dsconfigad -alldomains disable -localhome enable -groups "${ADMINGROUPS:-"domain admins,enterprise admins"}" -mobile enable -mobileconfirm disable -namespace domain -preferred "${ADDOMAIN}" -restrictDDNS en99 -enablesso 2>&1
