#!/bin/bash
# vi: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :

/usr/bin/defaults write /Library/Preferences/com.apple.screensaver loginWindowIdleTime 0
/usr/libexec/PlistBuddy -c print /Library/Preferences/com.apple.screensaver.plist
