#!/bin/bash
# vi: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :

OS_PRODUCT_NAME="$(/usr/bin/sw_vers -productName)"
OS_MAJOR_VERSION="$(/usr/bin/sw_vers -productVersion | awk -F. '{print $2}')"

if [ "$OS_MAJOR_VERSION" -gt 6 ]; then
    if [ ! -d /Applications/Server.app ]; then
        STATUS='N/A'
    else
        IsConfigured="$(
            serverinfo --configured >/dev/null
            echo $?
        )"
        if [ "$IsConfigured" -ne 0 ]; then
            STATUS='no'
        else
            STATUS='yes'
        fi
    fi
else
    if [ "$OS_PRODUCT_NAME" = "Mac OS X Server" ]; then
        STATUS='yes'
    else
        STATUS='N/A'
    fi
fi
echo "$STATUS"
