#!/bin/bash
# vi: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :

TOTAL_SIZE_BYTE="$(diskutil info / | grep 'Container Total Space:' | tr -d "()" | awk '{print $6}')"
FREE_SIZE_BYTE="$(diskutil info / | grep 'Container Free Space:' | tr -d "()" | awk '{print $6}')"

echo "$(echo "scale=1; ($TOTAL_SIZE_BYTE - $FREE_SIZE_BYTE ) / $TOTAL_SIZE_BYTE * 100 " | bc)" %
