#!/bin/bash

if [ -f /tmp/knot-resolver-working ]; then
    STATE="$( cat /tmp/knot-resolver-working )"
fi
if [ "${STATE:-9}" -eq 0 ]; then exit 0; fi

dig www.apple.com > /dev/null 2>&1
RET=$?
echo "$RET" > /tmp/knot-resolver-working
if [ $RET -eq 0 ]; then exit 0 ; fi

if [ ! -f /Library/LaunchDaemons/homebrew.mxcl.knot-resolver.plist ]; then
    exit 0
fi
brew services restart knot-resolver
