#!/bin/bash
# vim: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :
#-
#- Usage:
#-     codesigner [add|remove] /path/to/something.mobileconfig
#-

if [ $# -lt 2 ]; then
    grep ^#- "$0" | cut -c 4-
    exit 0
fi

mode="$1"
mobileconfig="$2"
tmpfile="/tmp/$(uuidgen)"

if [ ! -f "$mobileconfig" ]; then
    mode=none
    echo "Not found: $mobileconfig"
fi

case "${mode:-none}" in
    add)
        /usr/bin/security find-identity -p codesigning -v | awk -F\" '{print $2}' | awk NF >"$tmpfile"
        numOfresult="$(wc -l "$tmpfile" | awk '{print $1}')"
        if [ "$numOfresult" -eq 0 ]; then
            echo "No valid certificate in your keychain."
            rm "$tmpfile"
            exit 1
        elif [ "$numOfresult" -eq 1 ]; then
            cert="$(cat "$tmpfile")"
        else
            /bin/echo "Select one you want to use for code sign."
            awk '{print NR") "$0 }' "$tmpfile"
            while true; do
                /bin/echo -n "[ 1 - $numOfresult ]> "
                read -r NUM
                if ((NUM >= 1)) && ((NUM <= numOfresult)); then
                    cert="$(awk -v R="$NUM" 'NR == R {print $0}' "$tmpfile")"
                    break
                fi
            done
        fi
        rm -f "$tmpfile"
        /usr/bin/security cms -S -N "$cert" -i "$mobileconfig" -o "$tmpfile"
        r=$?
        ;;
    remove)
        /usr/bin/security cms -D -i "$mobileconfig" -o "$tmpfile"
        r=$?
        ;;
    *)
        grep ^#- "$0" | cut -c 4-
        exit 1
        ;;
esac

if [ ${r:-1} -eq 0 ]; then
    mv "$tmpfile" "$mobileconfig"
else
    rm -f "$tmpfile"
fi
