#!/bin/bash

docker_dlurl="https://download.docker.com/mac/stable/Docker.dmg"
docker_dmg="$( basename "$docker_dlurl" )"
docker_app="Docker.app"

kitematic_dlurl="https://download.docker.com/kitematic/Kitematic-Mac.zip"
kitematic_zip="$( basename "$kitematic_dlurl" )"
kitematic_app="Kitematic.app"

workdir="$( /usr/bin/mktemp -d )"

verbose=0
if [ "$verbose" -eq 0 ]; then
    curl_opt='-s'
    unzip_opt='-q'
else
    curl_opt=''
    unzip_opt=''
fi

eval /usr/bin/curl "$vurl_opt" -o "${workdir}/$docker_dmg" $docker_dlurl

eval /usr/bin/curl "$vurl_opt" -o "${workdir}/$kitematic_zip" $kitematic_dlurl
if [ -f "${workdir}/$kitematic_zip" ]; then
    eval unzip $unzip_opt "${workdir}/$kitematic_zip" -d "$workdir"
fi

rm -rf "$workdir"
