#!/bin/bash
# vim: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :
# https://github.com/taniguti/scripts_for_mac_manage/blob/master/LICENSE

if [ ! -f "$1" ]; then exit 0; fi

WORKDIR="$(mktemp -d)"
SCRIPTNAME="$(basename "$1")"
SERIAL="$(date +%Y%m%d-%H%M%S)"
DEVELOPERID="$(security find-certificate -a | grep alis | grep ')' | grep "Developer ID Installer" | awk -F= '{print $2}' | tr -d \")"

if [ -n "$DEVELOPERID" ]; then ADDSIGN="--sign"; fi
mkdir -p "${WORKDIR}/${SCRIPTNAME}/Scripts"
cp "$1" "${WORKDIR}/${SCRIPTNAME}/Scripts/postinstall"
chmod 755 "${WORKDIR}/${SCRIPTNAME}/Scripts/postinstall"

pkgbuild --identifier "scripts.for.mac.manage.tools.${SCRIPTNAME}.pkg" \
    --nopayload "$ADDSIGN" "$DEVELOPERID" \
    --scripts "${WORKDIR}/${SCRIPTNAME}/Scripts" "${WORKDIR}/${SCRIPTNAME}-${SERIAL}.pkg"

if [ -e "${WORKDIR}/${SCRIPTNAME}-${SERIAL}.pkg" ]; then
    mv "${WORKDIR}/${SCRIPTNAME}-${SERIAL}.pkg" "$HOME/Desktop"
    rm -rf "${WORKDIR}"
fi
