#!/bin/bash

function _readlink(){
    c="$1"
    f="$( /usr/bin/basename "$c" )"
    if [ "$( /usr/bin/type -a "$c" 2> /dev/null| /usr/bin/head -1 )"x = x ]; then
        d="$( cd "$(/usr/bin/dirname "$c" )" || exit 1; /bin/pwd )"
    else
        p="$( /usr/bin/type -a "$c" | /usr/bin/head -1 | /usr/bin/awk '{$1="";$2=""; print $0}'| /usr/bin/sed 's/^[ \t]*//' )"
        d="$( /usr/bin/dirname "$p" )"
    fi
    if [ -L "${d}/${f}" ]; then
        cd "${d}" || exit 1
        r="$( /usr/bin/readlink -n "${d}/${f}" )"
        _readlink "$r"
    else
        echo "${d}/${f}"
    fi
}

fullpath_to_me="$( _readlink "$0" )"
pathtome="$(/usr/bin/dirname "$fullpath_to_me" )"

dockerapp=/Applications/Docker.app
dockerplist="${dockerapp}/Contents/Resources/com.docker.vmnetd.plist"
dockerbindir="${dockerapp}/Contents/Resources/bin"
dockervmnetd="${dockerapp}/Contents/Library/LaunchServices/com.docker.vmnetd"
plistfile="$( /usr/bin/basename "$dockerplist" )"
macuser="$(stat -f %Su /dev/console)"
if [ "$macuser" = root ]; then
    echo "No user who aboards docker is logging in."
    echo "Abort"
    exit 1
fi

"${pathtome}/remove_quarantine" "$dockerapp"

/bin/mkdir -p /usr/local/bin /Library/PrivilegedHelperTools

if [ -f "$dockervmnetd" ]; then
    /bin/cp -af "$dockervmnetd" /Library/PrivilegedHelperTools/
fi

for cmd in $( /usr/bin/stat -f %N "${dockerbindir}"/*  )
do
    /bin/ln -fs "$cmd" "/usr/local/bin/"
done

if [ -f "$dockerplist" ]; then
    /bin/cp -af "$dockerplist" /Library/LaunchDaemons/
    /bin/chmod 644 "/Library/LaunchDaemons/$plistfile"
    /usr/sbin/chown 0:0 "/Library/LaunchDaemons/$plistfile"

    vmnetdStatus=$( /bin/launchctl list | /usr/bin/grep -c $( /usr/bin/basename "$plistfile" .plist ) )
    if [ "${vmnetdStatus:-0}" -eq 0 ]; then
        /bin/launchctl load -w "/Library/LaunchDaemons/$plistfile"
    else
        /bin/launchctl stop "/Library/LaunchDaemons/$plistfile"
        /bin/launchctl start "/Library/LaunchDaemons/$plistfile"
    fi
fi
