#!/bin/bash
# vim: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :
# https://github.com/taniguti/scripts_for_mac_manage/blob/master/LICENSE

# https://superuser.com/questions/619498/can-i-install-homebrew-without-sudo-privileges
set -ex

export HOMEBREW_PREFIX=$HOME/homebrew
# export HOMEBREW_NO_ANALYTICS=1
mkdir -p "${HOMEBREW_PREFIX}"
chflags hidden "${HOMEBREW_PREFIX}"
curl -fsSLk https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C "${HOMEBREW_PREFIX}"

export PATH="${HOMEBREW_PREFIX}/bin:${PATH}"
type -a brew

type -a openssl || :
openssl version -a || :

type -a curl || :
curl -V || :

# Fails to lock a .git/config file.
##brew analytics off

# No "brew update" until installing the proper openssl and a curl that uses it.
# brew update

# brew remove openssl || :
brew install openssl
brew link --force openssl

# brew remove curl || :
#brew install --with-openssl curl
brew install curl
brew link --force curl || :
curl -V

# shellcheck disable=SC2016
echo 'Add export PATH="${HOMEBREW_PREFIX}/bin:${PATH}" in your .bashrc'
