#!/bin/bash
# vim: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :
# https://github.com/taniguti/scripts_for_mac_manage/blob/master/LICENSE
#-
#- Notarization checker: (spctl wrapper)
#- https://github.com/taniguti/scripts_for_mac_manage/blob/master/LICENSE
#- --------------------
#- $ ./notarization-checker /path/to/hoge.app
#- /path/to/hoge.app: accepted (version: 0.1.2)
#- $ ./notarization-checker /path/to/fuga.app
#- /path/to/fuga.app: rejected (version: 3.4.5)
#- $ ./notarization-checker /path/to/piyo.pkg
#- /path/to/piyo.pkg: accepted
#-
#- Item must have extension, app,kext,dmg or pkg.
#-

if [ "$#" -eq 0 ]; then
    /usr/bin/grep '^#-' "$0" | cut -c 4-
    exit 0
fi

target="$1"
if [ ! -e "$target" ]; then
    echo "Not found: $target" >&2
    exit 1
fi

ext="$( echo "${target##*.}" | /usr/bin/tr "[:upper:]" "[:lower:]" )"
case "${ext%/}" in
    app | kext )
        if [ "${ext%/}" = kext ]; then
            ctype="install"
        else
            ctype="execute"
        fi
        result="$( /usr/sbin/spctl --assess --verbose --type "$ctype" "$target" 2>&1 | /usr/bin/grep "$target" )"
        target_version="$( /usr/libexec/PlistBuddy -c "print CFBundleShortVersionString" "${target}/Contents/Info.plist" 2> /dev/null )"
        echo "$result: (version ${target_version:-N/A})"
        ;;
    pkg )
       /usr/sbin/spctl --assess --verbose --type install "$target" 2>&1 | /usr/bin/grep "$target"
        ;;
    dmg )
       /usr/sbin/spctl --assess --verbose --type open --context "context:primary-signature" "$target" 2>&1 | /usr/bin/grep "$target"
        ;;
    *)
        echo "Unexpected extension: ${ext%/}" >&2
        echo "Either app, dmg, kext or pkg is expected." >&2
        exit 1
        ;;
esac
