#!/bin/bash
#
# https://github.com/taniguti/scripts_for_mac_manage/blob/master/tools/remove_garageband_sound_library
#
# MIT License
#
# Copyright (c) 2018 Takanori TANIGUCHI
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#-
#- Remove GarageBand and its Sound Libraries
#-

if [ "$( /usr/bin/whoami )" != 'root' ]; then
    echo "Use me with sudo."
    exit 1
fi

for item in "/Applications/GarageBand.app" \
            "/Library/Application Support/GarageBand" \
            "/Library/Audio/Apple Loops" \
            "/Library/Application Support/Logic" \
            "/Library/Audio/Apple Loops" \
            "/Library/Audio/Apple Loops Index"
do
    if [ -d "$item" ]; then
        /bin/echo "[REMOVE] $( /usr/bin/du -sh "$item" )"
        /bin/rm -rf "$item"
    fi
done

exit 0
