#!/bin/bash
#-
#- Usage:
#-   remove_quarantine application_name [application_name ... ]
#-

if [ $# -eq 0 ]; then
    grep ^#- "$0" | cut -c 4-
    exit 0
fi

for a in "$@"
do
    if [ -e "$a" ]; then
        DLAPP="$a"
    elif [ -e "/Applications/$a" ]; then
        DLAPP="/Applications/$a"
    elif [ -e "/Applications/Utilities/$a" ]; then
        DLAPP="/Applications/Utilities/$a"
    elif [ -e "$HOME/Applications/$a" ]; then
        DLAPP="$HOME/Applications/$a"
    else
        echo "Not found: $a"
        continue
    fi

    OWNER=$( stat -F "$DLAPP" | awk '{print $3}')
    
    if [ "$OWNER" = "$(whoami)" ]; then
        isMyown=yes
    else
        isMyown=no
    fi

    if [ "$isMyown" = yes ]; then
        xattr -r -d com.apple.quarantine "${DLAPP}"
    else
        sudo xattr -r -d com.apple.quarantine "${DLAPP}"
    fi
done
