#!/bin/bash
# vim: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :
# https://github.com/taniguti/scripts_for_mac_manage/blob/master/LICENSE
#-
#- Usage:
#-   remove_quarantine application_name [application_name ... ]
#-

if [ $# -eq 0 ]; then
    /usr/bin/grep ^#- "$0" | cut -c 4-
    exit 0
fi

for a in "$@"; do
    if [ -e "$a" ]; then
        DLAPP="$a"
    elif [ -e "/Applications/$a" ]; then
        DLAPP="/Applications/$a"
    elif [ -e "/Applications/Utilities/$a" ]; then
        DLAPP="/Applications/Utilities/$a"
    elif [ -e "$HOME/Applications/$a" ]; then
        DLAPP="$HOME/Applications/$a"
    else
        /bin/echo "Not found: $a"
        continue
    fi

    OWNER=$( /usr/bin/stat -F "$DLAPP" | /usr/bin/awk '{print $3}')

    if [ "$OWNER" = "$(/usr/bin/whoami)" ]; then
        isMyown=yes
    else
        isMyown=no
    fi

    if [ "$isMyown" = yes ]; then
        /usr/bin/xattr -r -d com.apple.quarantine "${DLAPP}"
    else
        /usr/bin/sudo /usr/bin/xattr -r -d com.apple.quarantine "${DLAPP}"
    fi
done
