#!/bin/bash

SL_LOGFILE=$( /usr/bin/mktemp )
function script-logger(){
    echo "[$(/bin/date +%F" "%T)] $*" | tee -a "$SL_LOGFILE"
}


script-logger "test 1 2 3"
sleep 2
script-logger "test 4 5 6"
echo "$SL_LOGFILE"
